
##########服务端口配置##########
server:
  port: 8888
  tomcat:
    max-http-header-size: 20000
    max-connections: 30000

##########mybatis配置##########
mybatis-plus:
  mapper-locations: classpath:mybatis-mapper/*.xml
  type-aliases-package: com.zz.module.user.pojo
#  type-aliases-package: com.zz.module.*.pojo
#  config-location:  classpath:mybatis-config.xml


##########数据库配置##########
spring:
  #  profiles:
  #    active: test
  datasource:
    #name: test
    url: jdbc:mariadb://192.168.1.187:3306/chuckweb?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.mariadb.jdbc.Driver
  aop:
    auto: true


