server:
  port: 8765
spring:
  application:
    name: service-feign

eureka:
  client:
    healthcheck:
      # 一定要启用健康检查
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    lease-renewal-interval-in-seconds: 45 # 用于定义服务续约任务的调用间隔时间，默认30秒
#    lease-expiration-duration-in-seconds: 90  # 用于定义服务失效的时间 ，默认90秒
feign:
  hystrix:
    enabled: true

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 2000  #修改Hystrix默认超时时间
